name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1.9

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Test
        working-directory: build
        run: ctest

      - name: Install
        run:  make install

      - name: Package
        run: cpack

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ./*.deb
